import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Forgot Password","description":"","frontmatter":{"outline":false,"examples":[{"id":"forgot-password","title":"Forgot Password","description":"Request a password reset email for an account.","query":"mutation createForgotPassword($email: String!) {\\n  createForgotPassword(input: {\\n    email: $email\\n  }) {\\n    forgotPassword {\\n      success\\n      message\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"email\\": \\"john.doe@example.com\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"forgotPassword\\": {\\n      \\"message\\": \\"Password reset link sent to your email\\",\\n      \\"success\\": true\\n    }\\n  }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/forgot-password.md","filePath":"api/graphql-api/shop/mutations/forgot-password.md","lastUpdated":1771002662000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/forgot-password.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="forgot-password" tabindex="-1">Forgot Password <a class="header-anchor" href="#forgot-password" aria-label="Permalink to &quot;Forgot Password&quot;">​</a></h1><p>Request a password reset email for an account.</p><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>email</code></td><td>String</td><td>✅ Yes</td><td>Customer&#39;s registered email address</td></tr></tbody></table><h2 id="response" tabindex="-1">Response <a class="header-anchor" href="#response" aria-label="Permalink to &quot;Response&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>message</code></td><td>String</td><td>Success or error message</td></tr><tr><td><code>success</code></td><td>Boolean</td><td>Request success status</td></tr></tbody></table><h2 id="behavior" tabindex="-1">Behavior <a class="header-anchor" href="#behavior" aria-label="Permalink to &quot;Behavior&quot;">​</a></h2><ul><li>Sends a password reset link to the customer&#39;s email</li><li>The reset link is valid for a configurable period (typically 24 hours)</li><li>Customer uses the link to set a new password</li><li>Old tokens are invalidated when password is reset</li></ul><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;email&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;No account found with this email address.&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="email-content" tabindex="-1">Email Content <a class="header-anchor" href="#email-content" aria-label="Permalink to &quot;Email Content&quot;">​</a></h2><p>The reset email typically contains:</p><ul><li>A unique password reset link/token</li><li>Expiration time for the token</li><li>Instructions to reset the password</li><li>Security information</li></ul><h2 id="next-steps" tabindex="-1">Next Steps <a class="header-anchor" href="#next-steps" aria-label="Permalink to &quot;Next Steps&quot;">​</a></h2><p>After requesting password reset:</p><ol><li>Customer receives email with reset link</li><li>Customer clicks the link</li><li>Customer enters new password</li><li>Customer uses <a href="/api/graphql-api/shop/mutations/reset-password.html">Reset Password</a> mutation to confirm</li></ol><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/reset-password.html">Reset Password</a></li><li><a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/forgot-password.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const forgotPassword = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  forgotPassword as default
};
