import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse(`{"title":"Delete Customer Account","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-customer-profile","title":"Delete Customer Account","description":"Permanently delete the authenticated customer's account.","query":"mutation deleteCustomerProfile {\\n  createCustomerProfileDelete(input: {}) {\\n    customerProfileDelete {\\n      id\\n    }\\n  } \\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"createCustomerProfileDelete\\": {\\n      \\"customerProfileDelete\\": null\\n    }\\n  }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/delete-customer-profile.md","filePath":"api/graphql-api/shop/mutations/delete-customer-profile.md","lastUpdated":1771002662000}`);
const _sfc_main = { name: "api/graphql-api/shop/mutations/delete-customer-profile.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-customer-account" tabindex="-1">Delete Customer Account <a class="header-anchor" href="#delete-customer-account" aria-label="Permalink to &quot;Delete Customer Account&quot;">​</a></h1><p>Permanently delete the authenticated customer&#39;s account and all associated data.</p><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This query requires a valid customer authentication token in the <code>Authorization</code> header. Use the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a> to retrieve the token.</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="important-notes" tabindex="-1">Important Notes <a class="header-anchor" href="#important-notes" aria-label="Permalink to &quot;Important Notes&quot;">​</a></h2><p>⚠️ <strong>This action is permanent and cannot be undone</strong></p><p>When a customer account is deleted:</p><ul><li>All personal information is removed</li><li>Order history is archived (for legal compliance)</li><li>Wishlist items are removed</li><li>Addresses are deleted</li><li>Authentication tokens are invalidated</li></ul><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;message&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Invalid or expired token&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/update-customer-profile.html">Update Customer Profile</a></li><li><a href="/api/graphql-api/shop/mutations/customer-logout.html">Customer Logout</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/delete-customer-profile.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteCustomerProfile = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteCustomerProfile as default
};
