import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Set Payment Method","description":"","frontmatter":{"outline":false,"examples":[{"id":"set-payment-method","title":"Set Payment Method","description":"Select a payment method for the order.","request":"POST /api/shop/checkout/payment-method\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\\n\\n{\\n  \\"payment\\": {\\n    \\"method\\": \\"paypal\\"\\n  }\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"paymentMethod\\": {\\n      \\"method\\": \\"paypal\\",\\n      \\"title\\": \\"PayPal\\",\\n      \\"description\\": \\"Pay securely with PayPal\\"\\n    }\\n  },\\n  \\"message\\": \\"Payment method set successfully\\"\\n}\\n","commonErrors":[{"error":"401 Unauthorized","cause":"Customer not authenticated","solution":"Provide valid Bearer token"},{"error":"422 Unprocessable Entity","cause":"Invalid payment method","solution":"Use method from get-payment-methods response"}]}]},"headers":[],"relativePath":"api/rest-api/shop/checkout/set-payment-method.md","filePath":"api/rest-api/shop/checkout/set-payment-method.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/checkout/set-payment-method.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="set-payment-method" tabindex="-1">Set Payment Method <a class="header-anchor" href="#set-payment-method" aria-label="Permalink to &quot;Set Payment Method&quot;">​</a></h1><p>Select a payment method for the order checkout.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>POST /api/shop/checkout/payment-method</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr><tr><td><code>Authorization</code></td><td>Yes</td><td>Bearer token (customer login required)</td></tr></tbody></table><h2 id="request-body" tabindex="-1">Request Body <a class="header-anchor" href="#request-body" aria-label="Permalink to &quot;Request Body&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;payment&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;method&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;paypal&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="payment-method-options" tabindex="-1">Payment Method Options <a class="header-anchor" href="#payment-method-options" aria-label="Permalink to &quot;Payment Method Options&quot;">​</a></h2><p>Common payment methods:</p><ul><li><code>paypal</code> - PayPal</li><li><code>stripe</code> - Stripe</li><li><code>cod</code> - Cash on Delivery</li><li><code>bank_transfer</code> - Bank Transfer</li></ul><h2 id="response-fields-200-ok" tabindex="-1">Response Fields (200 OK) <a class="header-anchor" href="#response-fields-200-ok" aria-label="Permalink to &quot;Response Fields (200 OK)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>paymentMethod</code></td><td>object</td><td>Selected payment method details</td></tr><tr><td><code>message</code></td><td>string</td><td>Success message</td></tr></tbody></table><h2 id="payment-method-fields" tabindex="-1">Payment Method Fields <a class="header-anchor" href="#payment-method-fields" aria-label="Permalink to &quot;Payment Method Fields&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>method</code></td><td>string</td><td>Payment method code</td></tr><tr><td><code>title</code></td><td>string</td><td>Display name</td></tr><tr><td><code>description</code></td><td>string</td><td>Method description</td></tr><tr><td><code>instructions</code></td><td>string</td><td>Payment instructions</td></tr></tbody></table><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Select PayPal payment</li><li>Choose credit card</li><li>Use cash on delivery</li><li>Select bank transfer</li><li>Finalize payment details</li></ul><h2 id="validation-rules" tabindex="-1">Validation Rules <a class="header-anchor" href="#validation-rules" aria-label="Permalink to &quot;Validation Rules&quot;">​</a></h2><ul><li>Payment method must be available</li><li>Must have valid billing address</li><li>Some methods restricted by location</li><li>Payment may require additional setup</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/checkout/get-payment-methods.html">Get Payment Methods</a></li><li><a href="/api/rest-api/shop/checkout/set-billing-address.html">Set Billing Address</a></li><li><a href="/api/rest-api/shop/checkout/place-order.html">Place Order</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/checkout/set-payment-method.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const setPaymentMethod = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  setPaymentMethod as default
};
