import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Get Channels","description":"","frontmatter":{"outline":false,"examples":[{"id":"get-channels","title":"Get All Channels","description":"Retrieve list of all store channels.","request":"GET /api/shop/channels\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\n","response":"{\\n  \\"data\\": [\\n    {\\n      \\"id\\": 1,\\n      \\"code\\": \\"default\\",\\n      \\"name\\": \\"Default Channel\\",\\n      \\"description\\": \\"Default website channel\\",\\n      \\"hostname\\": \\"example.com\\",\\n      \\"isActive\\": true\\n    },\\n    {\\n      \\"id\\": 2,\\n      \\"code\\": \\"mobile\\",\\n      \\"name\\": \\"Mobile Store\\",\\n      \\"description\\": \\"Mobile app channel\\",\\n      \\"hostname\\": \\"mobile.example.com\\",\\n      \\"isActive\\": true\\n    }\\n  ]\\n}\\n","commonErrors":[{"error":"401 Unauthorized","cause":"Invalid X-STOREFRONT-KEY","solution":"Provide valid storefront API key"}]}]},"headers":[],"relativePath":"api/rest-api/shop/channels/get-channels.md","filePath":"api/rest-api/shop/channels/get-channels.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/channels/get-channels.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="get-channels" tabindex="-1">Get Channels <a class="header-anchor" href="#get-channels" aria-label="Permalink to &quot;Get Channels&quot;">​</a></h1><p>Retrieve a list of all available store channels.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>GET /api/shop/channels</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr></tbody></table><h2 id="response-fields-200-ok" tabindex="-1">Response Fields (200 OK) <a class="header-anchor" href="#response-fields-200-ok" aria-label="Permalink to &quot;Response Fields (200 OK)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td>integer</td><td>Channel ID</td></tr><tr><td><code>code</code></td><td>string</td><td>Unique channel code</td></tr><tr><td><code>name</code></td><td>string</td><td>Channel display name</td></tr><tr><td><code>description</code></td><td>string</td><td>Channel description</td></tr><tr><td><code>hostname</code></td><td>string</td><td>Channel domain/hostname</td></tr><tr><td><code>isActive</code></td><td>boolean</td><td>Channel active status</td></tr><tr><td><code>logoUrl</code></td><td>string</td><td>Channel logo URL</td></tr><tr><td><code>faviconUrl</code></td><td>string</td><td>Channel favicon URL</td></tr></tbody></table><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Get available store channels</li><li>Display channel-specific information</li><li>Load channel configuration</li><li>Multi-channel store support</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/channels/get-channel.html">Single Channel</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/channels/get-channels.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getChannels = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getChannels as default
};
