import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Delete Product Review","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-product-review","title":"Delete Product Review","description":"Delete an existing product review.","request":"DELETE /api/shop/products/1/reviews/1\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\\n","response":"{\\n  \\"message\\": \\"Review deleted successfully\\"\\n}\\n","commonErrors":[{"error":"401 Unauthorized","cause":"Not authenticated or not review author","solution":"Ensure you own the review and provide valid token"},{"error":"403 Forbidden","cause":"User is not the review author","solution":"Only review author can delete their review"},{"error":"404 Not Found","cause":"Review does not exist","solution":"Verify the review ID"}]}]},"headers":[],"relativePath":"api/rest-api/shop/product-reviews/delete-product-review.md","filePath":"api/rest-api/shop/product-reviews/delete-product-review.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/product-reviews/delete-product-review.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-product-review" tabindex="-1">Delete Product Review <a class="header-anchor" href="#delete-product-review" aria-label="Permalink to &quot;Delete Product Review&quot;">​</a></h1><p>Delete an existing product review. Only the review author can delete their own review.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE /api/shop/products/{productId}/reviews/{reviewId}</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr><tr><td><code>Authorization</code></td><td>Yes</td><td>Bearer token (review author required)</td></tr></tbody></table><h2 id="path-parameters" tabindex="-1">Path Parameters <a class="header-anchor" href="#path-parameters" aria-label="Permalink to &quot;Path Parameters&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>productId</code></td><td>integer</td><td>Yes</td><td>Product ID</td></tr><tr><td><code>reviewId</code></td><td>integer</td><td>Yes</td><td>Review ID to delete</td></tr></tbody></table><h2 id="response-204-no-content" tabindex="-1">Response (204 No Content) <a class="header-anchor" href="#response-204-no-content" aria-label="Permalink to &quot;Response (204 No Content)&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>No response body</span></span></code></pre></div><h2 id="alternative-response-200-ok" tabindex="-1">Alternative Response (200 OK) <a class="header-anchor" href="#alternative-response-200-ok" aria-label="Permalink to &quot;Alternative Response (200 OK)&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;message&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Review deleted successfully&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Allow customers to remove their reviews</li><li>Delete inappropriate or accidental reviews</li><li>Clean up old reviews</li><li>Remove reviews if product opinion changes</li></ul><h2 id="permissions" tabindex="-1">Permissions <a class="header-anchor" href="#permissions" aria-label="Permalink to &quot;Permissions&quot;">​</a></h2><ul><li>Only review author can delete their review</li><li>Admin users can delete any review</li><li>Deletion is permanent</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/product-reviews/get-product-review.html">Get Product Review</a></li><li><a href="/api/rest-api/shop/product-reviews/create-product-review.html">Create Product Review</a></li><li><a href="/api/rest-api/shop/product-reviews/update-product-review.html">Update Product Review</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/product-reviews/delete-product-review.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteProductReview = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteProductReview as default
};
