import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Get Wishlist Item","description":"","frontmatter":{"outline":false,"examples":[{"id":"get-wishlist-by-id","title":"Get Single Wishlist Item","description":"Retrieve a specific wishlist item by its IRI.","query":"query GetWishlist($id: ID!) {\\n  wishlist(id: $id) {\\n    id\\n    _id\\n    product {\\n      id\\n      name\\n      price\\n      baseImageUrl\\n    }\\n    customer {\\n      id\\n      email\\n    }\\n    channel {\\n      id\\n      code\\n    }\\n    createdAt\\n    updatedAt\\n  }\\n}\\n","variables":"{\\n  \\"id\\": \\"/api/shop/wishlists/69\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"wishlist\\": {\\n      \\"id\\": \\"/api/shop/wishlists/69\\",\\n      \\"_id\\": 69,\\n      \\"product\\": {\\n        \\"id\\": \\"/api/shop/products/1\\",\\n        \\"name\\": \\"Sample Product\\",\\n        \\"price\\": \\"99.99\\",\\n        \\"baseImageUrl\\": \\"https://example.com/storage/product/1/sample-product.jpg\\"\\n      },\\n      \\"customer\\": {\\n        \\"id\\": \\"/api/shop/customers/1\\",\\n        \\"email\\": \\"customer@example.com\\"\\n      },\\n      \\"channel\\": {\\n        \\"id\\": \\"/api/shop/channels/1\\",\\n        \\"code\\": \\"default\\"\\n      },\\n      \\"createdAt\\": \\"2026-02-17T10:00:00+00:00\\",\\n      \\"updatedAt\\": \\"2026-02-17T10:00:00+00:00\\"\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"ITEM_NOT_FOUND","cause":"Wishlist item ID does not exist or does not belong to the customer","solution":"Use a valid wishlist item IRI from the wishlists collection query"},{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"}]}]},"headers":[],"relativePath":"api/graphql-api/shop/queries/get-wishlist.md","filePath":"api/graphql-api/shop/queries/get-wishlist.md","lastUpdated":1771521671000}');
const _sfc_main = { name: "api/graphql-api/shop/queries/get-wishlist.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="get-wishlist-item" tabindex="-1">Get Wishlist Item <a class="header-anchor" href="#get-wishlist-item" aria-label="Permalink to &quot;Get Wishlist Item&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>wishlist</code> query retrieves a single wishlist item by its IRI identifier. Use this query to:</p><ul><li>Fetch detailed information about a specific wishlist item</li><li>Display wishlist item details on a detail page</li><li>Verify a product exists in the customer&#39;s wishlist</li></ul><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This query requires customer authentication:</p><ul><li><strong>Authenticated customers</strong>: Provide a valid customer authentication token in the <code>Authorization</code> header. Obtain this token via the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a>.</li></ul><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>The IRI of the wishlist item (e.g. <code>/api/shop/wishlists/69</code>).</td></tr></tbody></table><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>IRI identifier (e.g. <code>/api/shop/wishlists/69</code>).</td></tr><tr><td><code>_id</code></td><td><code>Int!</code></td><td>Numeric identifier.</td></tr><tr><td><code>product</code></td><td><code>Product!</code></td><td>Associated product with id, name, price, etc.</td></tr><tr><td><code>customer</code></td><td><code>Customer!</code></td><td>Associated customer with id, email.</td></tr><tr><td><code>channel</code></td><td><code>Channel!</code></td><td>Associated channel with id, code.</td></tr><tr><td><code>createdAt</code></td><td><code>String</code></td><td>Timestamp when the item was added.</td></tr><tr><td><code>updatedAt</code></td><td><code>String</code></td><td>Timestamp when the item was last updated.</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/queries/get-wishlist.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getWishlist = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getWishlist as default
};
