import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Move Wishlist Item to Cart","description":"","frontmatter":{"outline":false,"examples":[{"id":"move-wishlist-to-cart-basic","title":"Move Wishlist Item to Cart","description":"Move a wishlist item to the shopping cart and remove it from the wishlist.","query":"mutation MoveWishlistToCart($input: moveWishlistToCartInput!) {\\n  moveWishlistToCart(input: $input) {\\n    wishlistToCart {\\n      message\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"input\\": {\\n    \\"wishlistItemId\\": 68,\\n    \\"quantity\\": 2\\n  }\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"moveWishlistToCart\\": {\\n      \\"wishlistToCart\\": {\\n        \\"message\\": \\"Item moved to cart successfully\\"\\n      }\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"},{"error":"ITEM_NOT_FOUND","cause":"Wishlist item does not exist or belongs to another customer","solution":"Use a valid wishlist item numeric _id"},{"error":"INVALID_QUANTITY","cause":"Quantity is less than 1 or invalid","solution":"Provide a positive integer quantity"},{"error":"OPTIONS_REQUIRED","cause":"Configurable product requires options to be selected","solution":"Provide the required product options when moving configurable products"}]},{"id":"move-wishlist-to-cart-default-qty","title":"Move Wishlist Item to Cart - Default Quantity","description":"Move a wishlist item to the cart with the default quantity of 1 by omitting the quantity field.","query":"mutation MoveWishlistToCart($input: moveWishlistToCartInput!) {\\n  moveWishlistToCart(input: $input) {\\n    wishlistToCart {\\n      message\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"input\\": {\\n    \\"wishlistItemId\\": 68\\n  }\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"moveWishlistToCart\\": {\\n      \\"wishlistToCart\\": {\\n        \\"message\\": \\"Item moved to cart successfully\\"\\n      }\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"ITEM_NOT_FOUND","cause":"Wishlist item does not exist","solution":"Use a valid wishlist item numeric _id"}]}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/move-wishlist-to-cart.md","filePath":"api/graphql-api/shop/mutations/move-wishlist-to-cart.md","lastUpdated":1771348498000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/move-wishlist-to-cart.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="move-wishlist-item-to-cart" tabindex="-1">Move Wishlist Item to Cart <a class="header-anchor" href="#move-wishlist-item-to-cart" aria-label="Permalink to &quot;Move Wishlist Item to Cart&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>moveWishlistToCart</code> mutation moves a product from the customer&#39;s wishlist directly into their shopping cart. Use this mutation to:</p><ul><li>Implement &quot;Move to Cart&quot; buttons on the wishlist page</li><li>Convert saved-for-later items into active cart items</li><li>Streamline the purchase flow from wishlist to checkout</li></ul><p>The item is removed from the wishlist after it is successfully added to the cart.</p><blockquote><p><strong>Note:</strong> <code>wishlistItemId</code> is the numeric <code>_id</code> of the wishlist item (not the IRI). The <code>quantity</code> field defaults to <code>1</code> if omitted.</p></blockquote><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This mutation requires customer authentication:</p><ul><li><strong>Authenticated customers</strong>: Provide a valid customer authentication token in the <code>Authorization</code> header. Obtain this token via the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a>.</li></ul><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>wishlistItemId</code></td><td><code>Int!</code></td><td>The numeric <code>_id</code> of the wishlist item to move (not the IRI).</td></tr><tr><td><code>quantity</code></td><td><code>Int</code></td><td>Number of units to add to cart. Defaults to <code>1</code> if omitted.</td></tr><tr><td><code>clientMutationId</code></td><td><code>String</code></td><td>Optional client-side mutation identifier for tracking.</td></tr></tbody></table><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>wishlistToCart.message</code></td><td><code>String!</code></td><td>Success message confirming the item was moved.</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/move-wishlist-to-cart.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const moveWishlistToCart = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  moveWishlistToCart as default
};
