import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Customer Login","description":"","frontmatter":{"outline":false,"examples":[{"id":"customer-login","title":"Customer Login","description":"Authenticate a customer with email and password.","query":"mutation createCustomerLogin(\\n  $email: String!\\n  $password: String!\\n) {\\n  createCustomerLogin(\\n    input: {\\n      email: $email\\n      password: $password\\n    }\\n  ) {\\n    customerLogin {\\n      id\\n      _id\\n      apiToken      \\n      token\\n      success\\n      message\\n    }\\n  }\\n}\\n","variables":"{\\n    \\"email\\": \\"john.doe@example.com\\",\\n    \\"password\\": \\"SecurePass@123\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"createCustomerLogin\\": {\\n      \\"customerLogin\\": {\\n        \\"id\\": \\"1\\",\\n        \\"_id\\": 1,\\n        \\"apiToken\\": \\"OOxDk2s06JCndg5FHb8WbfF6ZR8jGq23168m9gm37J9Cmz4xah8B8AFK0Cp95x...\\",\\n        \\"token\\": \\"1|xy56RHXcttcDnimTHVEGIeyxzMKAWX6MyICCsZTA7dc...\\",\\n        \\"success\\": true,\\n        \\"message\\": \\"You have logged in successfully\\"\\n      }\\n    }\\n  }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/customer-login.md","filePath":"api/graphql-api/shop/mutations/customer-login.md","lastUpdated":1771002662000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/customer-login.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="customer-login" tabindex="-1">Customer Login <a class="header-anchor" href="#customer-login" aria-label="Permalink to &quot;Customer Login&quot;">​</a></h1><p>Authenticate a customer account with email and password.</p><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>email</code></td><td>String</td><td>✅ Yes</td><td>Customer&#39;s email address</td></tr><tr><td><code>password</code></td><td>String</td><td>✅ Yes</td><td>Customer&#39;s password</td></tr></tbody></table><h2 id="response" tabindex="-1">Response <a class="header-anchor" href="#response" aria-label="Permalink to &quot;Response&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>createCustomerLogin</code></td><td>Customer</td><td>The authenticated customer login object</td></tr><tr><td><code>token</code></td><td>String</td><td>JWT token for API authentication</td></tr><tr><td><code>message</code></td><td>String</td><td>Success or error message</td></tr><tr><td><code>success</code></td><td>Boolean</td><td>Login success status</td></tr></tbody></table><h2 id="token-usage" tabindex="-1">Token Usage <a class="header-anchor" href="#token-usage" aria-label="Permalink to &quot;Token Usage&quot;">​</a></h2><p>Once logged in, use the <code>token</code> in the <code>Authorization</code> header for authenticated requests:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;token&gt;</span></span></code></pre></div><p>e.g.</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&quot;Authorization&quot;: &quot;Bearer 220|KZhQuUwUzb6Z7j.....&quot;</span></span></code></pre></div><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;email&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Invalid email or password.&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/customer-registration.html">Customer Registration</a></li><li><a href="/api/graphql-api/shop/mutations/customer-logout.html">Customer Logout</a></li><li><a href="/api/graphql-api/authentication.html">Authentication Guide</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/customer-login.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const customerLogin = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  customerLogin as default
};
