import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse(`{"title":"Get Customer Profile","description":"","frontmatter":{"outline":false,"examples":[{"id":"get-customer-profile","title":"Get Customer Profile","description":"Retrieve the authenticated customer's profile information.","query":"query getCustomerProfile {\\n  readCustomerProfile {\\n    id\\n    firstName\\n    lastName\\n    email\\n    dateOfBirth\\n    gender\\n    phone\\n    status\\n    subscribedToNewsLetter\\n    isVerified\\n    image\\n  }\\n}\\n","variables":"{}\\n","response":"{\\n  \\"data\\": {\\n    \\"readCustomerProfile\\": {\\n      \\"id\\": \\"/api/shop/customer-profiles/122\\",\\n      \\"firstName\\": \\"John\\",\\n      \\"lastName\\": \\"Doe\\",\\n      \\"email\\": \\"john.doe@example.com\\",\\n      \\"dateOfBirth\\": \\"1990-01-15\\",\\n      \\"gender\\": \\"Male\\",\\n      \\"phone\\": \\"555-0123\\",\\n      \\"status\\": \\"1\\",\\n      \\"subscribedToNewsLetter\\": true,\\n      \\"isVerified\\": \\"1\\",\\n      \\"image\\": null\\n    }\\n  }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/queries/get-customer-profile.md","filePath":"api/graphql-api/shop/queries/get-customer-profile.md","lastUpdated":1771437226000}`);
const _sfc_main = { name: "api/graphql-api/shop/queries/get-customer-profile.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="get-customer-profile" tabindex="-1">Get Customer Profile <a class="header-anchor" href="#get-customer-profile" aria-label="Permalink to &quot;Get Customer Profile&quot;">​</a></h1><p>Retrieve the authenticated customer&#39;s profile information.</p><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This query requires a valid customer authentication token in the <code>Authorization</code> header. Use the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a> to retrieve the token.</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><p>This query has no required arguments.</p><h2 id="response" tabindex="-1">Response <a class="header-anchor" href="#response" aria-label="Permalink to &quot;Response&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td>String</td><td>Customer ID</td></tr><tr><td><code>firstName</code></td><td>String</td><td>First name</td></tr><tr><td><code>lastName</code></td><td>String</td><td>Last name</td></tr><tr><td><code>email</code></td><td>String</td><td>Email address</td></tr><tr><td><code>dateOfBirth</code></td><td>String</td><td>Date of birth (YYYY-MM-DD)</td></tr><tr><td><code>gender</code></td><td>String</td><td>Gender (male/female/other)</td></tr><tr><td><code>phone</code></td><td>String</td><td>Phone number</td></tr></tbody></table><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Display customer account information</li><li>Show profile on account dashboard</li><li>Verify customer information</li><li>Pre-fill form fields</li></ul><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;authentication&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Unauthenticated. Please login to perform this action&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/update-customer-profile.html">Update Customer Profile</a></li><li><a href="/api/graphql-api/shop/queries/get-customer-orders.html">Get Customer Orders</a></li><li><a href="/api/graphql-api/shop/queries/get-customer-addresses.html">Get Customer Addresses</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/queries/get-customer-profile.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getCustomerProfile = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getCustomerProfile as default
};
