import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Create Cart","description":"","frontmatter":{"outline":false,"examples":[{"id":"create-cart","title":"Create Cart","description":"Create a new shopping cart.","request":"POST /api/shop/cart\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\n","response":"{\\n  \\"data\\": {\\n    \\"id\\": 1,\\n    \\"items\\": [],\\n    \\"subtotal\\": 0,\\n    \\"tax\\": 0,\\n    \\"shippingCost\\": 0,\\n    \\"total\\": 0,\\n    \\"itemCount\\": 0,\\n    \\"couponCode\\": null,\\n    \\"createdAt\\": \\"2024-01-20T15:30:00Z\\"\\n  },\\n  \\"message\\": \\"Cart created successfully\\"\\n}\\n","commonErrors":[{"error":"400 Bad Request","cause":"Cart already exists","solution":"Use existing cart or clear it first"},{"error":"401 Unauthorized","cause":"Invalid X-STOREFRONT-KEY","solution":"Provide valid storefront API key"}]}]},"headers":[],"relativePath":"api/rest-api/shop/cart/create-cart.md","filePath":"api/rest-api/shop/cart/create-cart.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/cart/create-cart.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="create-cart" tabindex="-1">Create Cart <a class="header-anchor" href="#create-cart" aria-label="Permalink to &quot;Create Cart&quot;">​</a></h1><p>Create a new shopping cart. A new cart is typically created at the start of a shopping session.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>POST /api/shop/cart</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr></tbody></table><h2 id="request-body" tabindex="-1">Request Body <a class="header-anchor" href="#request-body" aria-label="Permalink to &quot;Request Body&quot;">​</a></h2><p>Optional. Can be empty <code>{}</code> or include initial items:</p><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;items&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;productId&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;quantity&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;attributes&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        &quot;color&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Black&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="response-fields-201-created" tabindex="-1">Response Fields (201 Created) <a class="header-anchor" href="#response-fields-201-created" aria-label="Permalink to &quot;Response Fields (201 Created)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td>integer</td><td>Cart ID</td></tr><tr><td><code>items</code></td><td>array</td><td>Items in cart (empty if newly created)</td></tr><tr><td><code>subtotal</code></td><td>decimal</td><td>Items subtotal</td></tr><tr><td><code>tax</code></td><td>decimal</td><td>Calculated tax</td></tr><tr><td><code>shippingCost</code></td><td>decimal</td><td>Shipping cost</td></tr><tr><td><code>total</code></td><td>decimal</td><td>Grand total</td></tr><tr><td><code>itemCount</code></td><td>integer</td><td>Total items in cart</td></tr><tr><td><code>couponCode</code></td><td>string</td><td>Applied coupon code (if any)</td></tr><tr><td><code>createdAt</code></td><td>string</td><td>Cart creation timestamp</td></tr></tbody></table><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Create cart at start of shopping session</li><li>Initialize empty cart for customer</li><li>Set up cart for guest checkout</li><li>Prepare cart for adding items</li></ul><h2 id="notes" tabindex="-1">Notes <a class="header-anchor" href="#notes" aria-label="Permalink to &quot;Notes&quot;">​</a></h2><ul><li>Cart is typically created once per session</li><li>Multiple carts can exist (for different users)</li><li>Empty carts can expire after inactivity</li><li>Cart ID is needed for subsequent operations</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/cart/get-cart.html">Get Cart</a></li><li><a href="/api/rest-api/shop/cart/add-to-cart.html">Add to Cart</a></li><li><a href="/api/rest-api/shop/cart/update-cart-item.html">Update Cart Item</a></li><li><a href="/api/rest-api/shop/cart/remove-cart-item.html">Remove Cart Item</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/cart/create-cart.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const createCart = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  createCart as default
};
