import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Update Product Review","description":"","frontmatter":{"outline":false,"examples":[{"id":"update-product-review","title":"Update Product Review","description":"Update an existing product review.","request":"PUT /api/shop/products/1/reviews/1\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\\n\\n{\\n  \\"title\\": \\"Great product!\\",\\n  \\"comment\\": \\"Updated review - even better than expected\\",\\n  \\"rating\\": 5\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"id\\": 1,\\n    \\"productId\\": 1,\\n    \\"title\\": \\"Great product!\\",\\n    \\"comment\\": \\"Updated review - even better than expected\\",\\n    \\"rating\\": 5,\\n    \\"authorName\\": \\"John Doe\\",\\n    \\"authorEmail\\": \\"john@example.com\\",\\n    \\"status\\": \\"pending\\",\\n    \\"updatedAt\\": \\"2024-01-21T10:15:00Z\\"\\n  },\\n  \\"message\\": \\"Review updated successfully\\"\\n}\\n","commonErrors":[{"error":"401 Unauthorized","cause":"Not authenticated or not review author","solution":"Ensure you own the review and provide valid token"},{"error":"403 Forbidden","cause":"User is not the review author","solution":"Only review author can update their review"},{"error":"404 Not Found","cause":"Review does not exist","solution":"Verify the review ID"}]}]},"headers":[],"relativePath":"api/rest-api/shop/product-reviews/update-product-review.md","filePath":"api/rest-api/shop/product-reviews/update-product-review.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/product-reviews/update-product-review.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="update-product-review" tabindex="-1">Update Product Review <a class="header-anchor" href="#update-product-review" aria-label="Permalink to &quot;Update Product Review&quot;">​</a></h1><p>Update an existing product review. Only the review author can update their own review.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>PUT /api/shop/products/{productId}/reviews/{reviewId}</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr><tr><td><code>Authorization</code></td><td>Yes</td><td>Bearer token (review author required)</td></tr></tbody></table><h2 id="path-parameters" tabindex="-1">Path Parameters <a class="header-anchor" href="#path-parameters" aria-label="Permalink to &quot;Path Parameters&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>productId</code></td><td>integer</td><td>Yes</td><td>Product ID</td></tr><tr><td><code>reviewId</code></td><td>integer</td><td>Yes</td><td>Review ID to update</td></tr></tbody></table><h2 id="request-body" tabindex="-1">Request Body <a class="header-anchor" href="#request-body" aria-label="Permalink to &quot;Request Body&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;title&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;string&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;comment&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;string&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;rating&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;integer (1-5)&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>title</code></td><td>string</td><td>No</td><td>Updated review title</td></tr><tr><td><code>comment</code></td><td>string</td><td>No</td><td>Updated review content</td></tr><tr><td><code>rating</code></td><td>integer</td><td>No</td><td>Updated rating (1-5)</td></tr></tbody></table><h2 id="response-fields-200-ok" tabindex="-1">Response Fields (200 OK) <a class="header-anchor" href="#response-fields-200-ok" aria-label="Permalink to &quot;Response Fields (200 OK)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td>integer</td><td>Review ID</td></tr><tr><td><code>productId</code></td><td>integer</td><td>Product ID</td></tr><tr><td><code>title</code></td><td>string</td><td>Review title</td></tr><tr><td><code>comment</code></td><td>string</td><td>Review content</td></tr><tr><td><code>rating</code></td><td>integer</td><td>Star rating</td></tr><tr><td><code>authorName</code></td><td>string</td><td>Reviewer name</td></tr><tr><td><code>authorEmail</code></td><td>string</td><td>Reviewer email</td></tr><tr><td><code>status</code></td><td>string</td><td>Review status</td></tr><tr><td><code>updatedAt</code></td><td>string</td><td>Last update timestamp</td></tr></tbody></table><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Allow customers to edit their reviews</li><li>Update reviews based on new experience</li><li>Correct mistakes or typos in reviews</li><li>Change ratings if opinion changes</li></ul><h2 id="permissions" tabindex="-1">Permissions <a class="header-anchor" href="#permissions" aria-label="Permalink to &quot;Permissions&quot;">​</a></h2><ul><li>Only review author can update their review</li><li>Admin users can update any review</li><li>Updated reviews may require re-approval</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/product-reviews/get-product-review.html">Get Product Review</a></li><li><a href="/api/rest-api/shop/product-reviews/create-product-review.html">Create Product Review</a></li><li><a href="/api/rest-api/shop/product-reviews/delete-product-review.html">Delete Product Review</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/product-reviews/update-product-review.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const updateProductReview = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  updateProductReview as default
};
