import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Get Compare Item","description":"","frontmatter":{"outline":false,"examples":[{"id":"get-compare-item-by-id","title":"Get Single Compare Item","description":"Retrieve a specific compare item by its IRI.","query":"query GetCompareItem($id: ID!) {\\n  compareItem(id: $id) {\\n    id\\n    _id\\n    product {\\n      id\\n      name\\n      price\\n      sku\\n    }\\n    customer {\\n      id\\n      email\\n      firstName\\n    }\\n    createdAt\\n    updatedAt\\n  }\\n}\\n","variables":"{\\n  \\"id\\": \\"/api/shop/compare-items/606\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"compareItem\\": {\\n      \\"id\\": \\"/api/shop/compare-items/606\\",\\n      \\"_id\\": 606,\\n      \\"product\\": {\\n        \\"id\\": \\"/api/shop/products/4\\",\\n        \\"name\\": \\"Laptop Pro 15\\",\\n        \\"price\\": \\"1299.99\\",\\n        \\"sku\\": \\"LP15-2026\\"\\n      },\\n      \\"customer\\": {\\n        \\"id\\": \\"/api/shop/customers/1\\",\\n        \\"email\\": \\"john@example.com\\",\\n        \\"firstName\\": \\"John\\"\\n      },\\n      \\"createdAt\\": \\"2026-02-17T10:30:00+00:00\\",\\n      \\"updatedAt\\": \\"2026-02-17T10:30:00+00:00\\"\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"ITEM_NOT_FOUND","cause":"Compare item ID does not exist or does not belong to the customer","solution":"Use a valid compare item IRI from the compareItems collection query"},{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"}]}]},"headers":[],"relativePath":"api/graphql-api/shop/queries/get-compare-item.md","filePath":"api/graphql-api/shop/queries/get-compare-item.md","lastUpdated":1771348498000}');
const _sfc_main = { name: "api/graphql-api/shop/queries/get-compare-item.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="get-compare-item" tabindex="-1">Get Compare Item <a class="header-anchor" href="#get-compare-item" aria-label="Permalink to &quot;Get Compare Item&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>compareItem</code> query retrieves a single compare item by its IRI identifier. Use this query to:</p><ul><li>Fetch detailed information about a specific compare item</li><li>Display product comparison details on a detail page</li><li>Verify a product exists in the customer&#39;s comparison list</li></ul><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This query requires customer authentication:</p><ul><li><strong>Authenticated customers</strong>: Provide a valid customer authentication token in the <code>Authorization</code> header. Obtain this token via the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a>.</li></ul><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>The IRI of the compare item (e.g. <code>/api/shop/compare-items/606</code>).</td></tr></tbody></table><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>IRI identifier (e.g. <code>/api/shop/compare-items/606</code>).</td></tr><tr><td><code>_id</code></td><td><code>Int!</code></td><td>Numeric identifier.</td></tr><tr><td><code>product</code></td><td><code>Product!</code></td><td>Associated product with id, name, sku, price, description, etc.</td></tr><tr><td><code>customer</code></td><td><code>Customer!</code></td><td>Associated customer with id, email, firstName, lastName.</td></tr><tr><td><code>createdAt</code></td><td><code>String</code></td><td>Timestamp when the item was added.</td></tr><tr><td><code>updatedAt</code></td><td><code>String</code></td><td>Timestamp when the item was last updated.</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/queries/get-compare-item.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getCompareItem = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getCompareItem as default
};
