import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Delete Product","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-product-simple","title":"Delete Product","description":"Delete a product from the system.","query":"mutation deleteProduct($id: ID!) {\\n  deleteProduct(id: $id) {\\n    message\\n    success\\n  }\\n}\\n","variables":"{\\n  \\"id\\": \\"1\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"deleteProduct\\": {\\n      \\"message\\": \\"Product deleted successfully\\",\\n      \\"success\\": true\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"PRODUCT_NOT_FOUND","cause":"Product ID does not exist","solution":"Verify product ID"},{"error":"CANNOT_DELETE_PRODUCT","cause":"Product cannot be deleted (e.g., has orders)","solution":"Check related records before deletion"}]}]},"headers":[],"relativePath":"api/graphql-api/admin/mutations/delete-product.md","filePath":"api/graphql-api/admin/mutations/delete-product.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/graphql-api/admin/mutations/delete-product.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-product" tabindex="-1">Delete Product <a class="header-anchor" href="#delete-product" aria-label="Permalink to &quot;Delete Product&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>deleteProduct</code> mutation removes a product from your store catalog. Use this mutation to:</p><ul><li>Remove discontinued or unwanted products</li><li>Clean up test/draft products</li><li>Manage product lifecycle</li><li>Delete products via API integrations</li><li>Bulk remove products from external feeds</li><li>Maintain accurate product catalogs</li></ul><p>This mutation performs validation checks (e.g., product has no active orders) before deletion to maintain data integrity.</p><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>The product ID to delete.</td></tr><tr><td><code>force</code></td><td><code>Boolean</code></td><td>Force deletion even if product has related data. Default: <code>false</code></td></tr></tbody></table><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>message</code></td><td><code>String!</code></td><td>Success or error message.</td></tr><tr><td><code>success</code></td><td><code>Boolean!</code></td><td>Indicates successful deletion.</td></tr><tr><td><code>deletedProductId</code></td><td><code>ID</code></td><td>ID of deleted product.</td></tr><tr><td><code>errors</code></td><td><code>[ErrorMessage!]</code></td><td>Validation errors if deletion failed.</td></tr><tr><td><code>warnings</code></td><td><code>[String!]</code></td><td>Warnings about related data (e.g., orphaned reviews).</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/admin/mutations/delete-product.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteProduct = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteProduct as default
};
