import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Setup & Configuration","description":"","frontmatter":{},"headers":[],"relativePath":"api/setup.md","filePath":"api/setup.md","lastUpdated":1770120989000}');
const _sfc_main = { name: "api/setup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="setup-configuration" tabindex="-1">Setup &amp; Configuration <a class="header-anchor" href="#setup-configuration" aria-label="Permalink to &quot;Setup &amp; Configuration&quot;">​</a></h1><p>Get the Bagisto API up and running in just a few minutes. Choose the installation method that works best for your setup.</p><h2 id="prerequisites" tabindex="-1">Prerequisites <a class="header-anchor" href="#prerequisites" aria-label="Permalink to &quot;Prerequisites&quot;">​</a></h2><p>Before installing, ensure you have:</p><ul><li><strong>Bagisto v2.0 or higher</strong> (<a href="https://devdocs.bagisto.com/getting-started/installation" target="_blank" rel="noreferrer">Bagisto Installation Guide</a>)</li><li><strong>Composer 2.0+</strong></li></ul><h2 id="installation-methods" tabindex="-1">Installation Methods <a class="header-anchor" href="#installation-methods" aria-label="Permalink to &quot;Installation Methods&quot;">​</a></h2><h3 id="method-1-quick-start-composer-installation-–-recommended" tabindex="-1">Method 1: Quick Start (Composer Installation – Recommended) <a class="header-anchor" href="#method-1-quick-start-composer-installation-–-recommended" aria-label="Permalink to &quot;Method 1: Quick Start (Composer Installation – Recommended)&quot;">​</a></h3><p>The fastest way to get started:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 1. Install the Bagisto API package</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">composer</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> require</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> bagisto/bagisto-api</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 2. Run the installer</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">php</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> artisan</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> bagisto-api-platform:install</span></span></code></pre></div><p>Your APIs are now ready! Access them at:</p><ul><li><strong>API Documentation</strong>: <code>https://your-domain.com/api</code><br> (e.g., <a href="https://api-demo.bagisto.com/api" target="_blank" rel="noreferrer">https://api-demo.bagisto.com/api</a>)</li></ul><h3 id="method-2-manual-installation" tabindex="-1">Method 2: Manual Installation <a class="header-anchor" href="#method-2-manual-installation" aria-label="Permalink to &quot;Method 2: Manual Installation&quot;">​</a></h3><p>Use this method if you need more control over the setup.</p><h4 id="step-1-download-and-extract" tabindex="-1">Step 1: Download and Extract <a class="header-anchor" href="#step-1-download-and-extract" aria-label="Permalink to &quot;Step 1: Download and Extract&quot;">​</a></h4><ol><li>Download the BagistoApi package from <a href="https://github.com/bagisto/bagisto-api" target="_blank" rel="noreferrer">GitHub</a></li><li>Extract it to: <code>packages/Webkul/BagistoApi/</code></li></ol><h4 id="step-2-register-service-provider" tabindex="-1">Step 2: Register Service Provider <a class="header-anchor" href="#step-2-register-service-provider" aria-label="Permalink to &quot;Step 2: Register Service Provider&quot;">​</a></h4><p>Edit <code>bootstrap/providers.php</code>:</p><div class="language-php vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">php</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">&lt;?</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">php</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">    // ...existing providers...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    Webkul\\BagistoApi\\Providers\\BagistoApiServiceProvider</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">::class</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">    // ...rest of providers...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">];</span></span></code></pre></div><h4 id="step-3-update-autoloading" tabindex="-1">Step 3: Update Autoloading <a class="header-anchor" href="#step-3-update-autoloading" aria-label="Permalink to &quot;Step 3: Update Autoloading&quot;">​</a></h4><p>Edit <code>composer.json</code> and update the <code>autoload</code> section:</p><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;autoload&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;psr-4&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;Webkul\\\\BagistoApi\\\\&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;packages/Webkul/BagistoApi/src&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h4 id="step-4-install-dependencies" tabindex="-1">Step 4: Install Dependencies <a class="header-anchor" href="#step-4-install-dependencies" aria-label="Permalink to &quot;Step 4: Install Dependencies&quot;">​</a></h4><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Install required packages</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">composer</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> require</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> api-platform/laravel:v4.1.25</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">composer</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> require</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> api-platform/graphql:v4.2.3</span></span></code></pre></div><h4 id="step-5-run-the-installation" tabindex="-1">Step 5: Run the installation <a class="header-anchor" href="#step-5-run-the-installation" aria-label="Permalink to &quot;Step 5: Run the installation&quot;">​</a></h4><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">composer</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dump-autoload</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">php</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> artisan</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> bagisto-api-platform:install</span></span></code></pre></div><h4 id="step-9-environment-setup-update-in-the-env" tabindex="-1">Step 9: Environment Setup (Update in the .env) <a class="header-anchor" href="#step-9-environment-setup-update-in-the-env" aria-label="Permalink to &quot;Step 9: Environment Setup (Update in the .env)&quot;">​</a></h4><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>STOREFRONT_DEFAULT_RATE_LIMIT=100</span></span>
<span class="line"><span>STOREFRONT_CACHE_TTL=60</span></span>
<span class="line"><span>STOREFRONT_KEY_PREFIX=storefront_key_</span></span>
<span class="line"><span>STOREFRONT_PLAYGROUND_KEY=pk_storefront_vxLIYv5PIp7jkujPNGLFQoDvIdsh2RMF </span></span>
<span class="line"><span>API_PLAYGROUND_AUTO_INJECT_STOREFRONT_KEY=true</span></span></code></pre></div><h3 id="access-points" tabindex="-1">Access Points <a class="header-anchor" href="#access-points" aria-label="Permalink to &quot;Access Points&quot;">​</a></h3><p>Once verified, access the APIs at:</p><ul><li><strong>API Documentation</strong>: <a href="https://api-demo.bagisto.com/api" target="_blank" rel="noreferrer">https://your-domain.com/api</a></li><li><strong>REST API (Shop)</strong>: <a href="https://api-demo.bagisto.com/api/shop" target="_blank" rel="noreferrer">https://your-domain.com/api/shop</a></li><li><strong>REST API (Admin)</strong>: <a href="https://api-demo.bagisto.com/api/admin" target="_blank" rel="noreferrer">https://your-domain.com/api/admin</a></li><li><strong>GraphQL Endpoint</strong>: <code>https://your-domain.com/api/graphql</code></li><li><strong>GraphQL Playground</strong>: <a href="https://api-demo.bagisto.com/api/graphiql" target="_blank" rel="noreferrer">https://your-domain.com/api/graphiql</a></li></ul><h2 id="troubleshooting" tabindex="-1">Troubleshooting <a class="header-anchor" href="#troubleshooting" aria-label="Permalink to &quot;Troubleshooting&quot;">​</a></h2><h3 id="provider-not-found" tabindex="-1">Provider Not Found <a class="header-anchor" href="#provider-not-found" aria-label="Permalink to &quot;Provider Not Found&quot;">​</a></h3><p><strong>Error</strong>: <code>Class &#39;Webkul\\BagistoApi\\Providers\\BagistoApiServiceProvider&#39; not found</code></p><p><strong>Solution</strong>:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">composer</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dump-autoload</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">php</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> artisan</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> cache:clear</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">php</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> artisan</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> config:clear</span></span></code></pre></div><h3 id="_404-errors-on-api-endpoints" tabindex="-1">404 Errors on API Endpoints <a class="header-anchor" href="#_404-errors-on-api-endpoints" aria-label="Permalink to &quot;404 Errors on API Endpoints&quot;">​</a></h3><p><strong>Error</strong>: API endpoints return 404 Not Found</p><p><strong>Solutions</strong>:</p><ol><li>Ensure routes are published: <code>php artisan vendor:publish --tag=routes</code></li><li>Clear route cache: <code>php artisan route:clear</code></li><li>Check <code>.htaccess</code> file is present in your web root</li><li>Verify <code>APP_URL</code> in <code>.env</code> matches your domain</li></ol><h3 id="permission-denied-errors" tabindex="-1">Permission Denied Errors <a class="header-anchor" href="#permission-denied-errors" aria-label="Permalink to &quot;Permission Denied Errors&quot;">​</a></h3><p><strong>Error</strong>: <code>Permission denied</code> on file operations</p><p><strong>Solution</strong>:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Set proper permissions</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">chmod</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -R</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 775</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> storage</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> bootstrap/cache</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">chmod</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -R</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 755</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> public</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># If using Docker/VM</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">chown</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -R</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> www-data:www-data</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> storage</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> bootstrap</span></span></code></pre></div><h3 id="database-connection-errors" tabindex="-1">Database Connection Errors <a class="header-anchor" href="#database-connection-errors" aria-label="Permalink to &quot;Database Connection Errors&quot;">​</a></h3><p><strong>Error</strong>: <code>SQLSTATE[HY000]: General error: 1030 Got error</code></p><p><strong>Solutions</strong>:</p><ol><li>Verify database credentials in <code>.env</code></li><li>Run migrations: <code>php artisan migrate</code></li><li>Check database encoding: <code>utf8mb4</code></li><li>Ensure sufficient disk space</li></ol><h3 id="rate-limiting-issues" tabindex="-1">Rate Limiting Issues <a class="header-anchor" href="#rate-limiting-issues" aria-label="Permalink to &quot;Rate Limiting Issues&quot;">​</a></h3><p><strong>Error</strong>: <code>429 Too Many Requests</code></p><p><strong>Solutions</strong>:</p><ol><li>Check rate limit configuration: <code>php artisan config:show bagisto-api</code></li><li>Update rate limit in <code>.env</code>: <code>BAGISTO_API_RATE_LIMIT=200</code></li><li>Clear rate limit cache: <code>php artisan cache:forget rate_limit</code></li></ol><h3 id="cors-errors-in-browser" tabindex="-1">CORS Errors in Browser <a class="header-anchor" href="#cors-errors-in-browser" aria-label="Permalink to &quot;CORS Errors in Browser&quot;">​</a></h3><p><strong>Error</strong>: <code>Access to XMLHttpRequest blocked by CORS policy</code></p><p><strong>Solutions</strong>:</p><ol><li>Verify CORS is configured in <code>config/cors.php</code></li><li>Check <code>FRONTEND_URL</code> environment variable</li><li>Ensure <code>supports_credentials</code> is set properly</li><li>Clear browser cache</li></ol><h2 id="performance-optimization" tabindex="-1">Performance Optimization <a class="header-anchor" href="#performance-optimization" aria-label="Permalink to &quot;Performance Optimization&quot;">​</a></h2><p>Ensure the application is running in a production environment and that APP_DEBUG is set to false.</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Clear cached configuration and other optimized files</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">php</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> artisan</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> optimize:clear</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Rebuild and optimize caches</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">php</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> artisan</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> optimize</span></span></code></pre></div><h2 id="what-s-next" tabindex="-1">What&#39;s Next? <a class="header-anchor" href="#what-s-next" aria-label="Permalink to &quot;What&#39;s Next?&quot;">​</a></h2><p>Ready to start using the APIs?</p><ul><li>🔐 <a href="./authentication.html">Authentication Guide</a> - Learn about authentication methods</li><li>🔗 <a href="./rest-api/introduction.html">REST API Guide</a> - Explore REST API endpoints</li><li>⚡ <a href="./graphql-api/introduction.html">GraphQL API Guide</a> - Discover GraphQL capabilities</li><li>🔑 <a href="./storefront-api-key-management-guide.html">API Key Management</a> - Generate and manage API keys</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/setup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const setup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  setup as default
};
