import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Remove Cart Item","description":"","frontmatter":{"outline":false,"examples":[{"id":"remove-cart-item","title":"Remove Item from Cart","description":"Remove a product from the shopping cart.","request":"DELETE /api/shop/cart/items/1\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\n","response":"{\\n  \\"message\\": \\"Item removed from cart successfully\\",\\n  \\"cartTotal\\": 0\\n}\\n","commonErrors":[{"error":"404 Not Found","cause":"Cart item does not exist","solution":"Verify the cart item ID"},{"error":"400 Bad Request","cause":"Cannot remove last item","solution":"Leave item in cart or create new cart"}]}]},"headers":[],"relativePath":"api/rest-api/shop/cart/remove-cart-item.md","filePath":"api/rest-api/shop/cart/remove-cart-item.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/cart/remove-cart-item.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="remove-cart-item" tabindex="-1">Remove Cart Item <a class="header-anchor" href="#remove-cart-item" aria-label="Permalink to &quot;Remove Cart Item&quot;">​</a></h1><p>Remove a product item from the shopping cart.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE /api/shop/cart/items/{itemId}</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr></tbody></table><h2 id="path-parameters" tabindex="-1">Path Parameters <a class="header-anchor" href="#path-parameters" aria-label="Permalink to &quot;Path Parameters&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>itemId</code></td><td>integer</td><td>Yes</td><td>Cart item ID</td></tr></tbody></table><h2 id="response-200-ok" tabindex="-1">Response (200 OK) <a class="header-anchor" href="#response-200-ok" aria-label="Permalink to &quot;Response (200 OK)&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;message&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Item removed from cart successfully&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;cartTotal&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">2999.95</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>message</code></td><td>string</td><td>Success message</td></tr><tr><td><code>cartTotal</code></td><td>decimal</td><td>Updated cart total</td></tr></tbody></table><h2 id="alternative-response-204-no-content" tabindex="-1">Alternative Response (204 No Content) <a class="header-anchor" href="#alternative-response-204-no-content" aria-label="Permalink to &quot;Alternative Response (204 No Content)&quot;">​</a></h2><p>No response body returned.</p><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Remove unwanted items from cart</li><li>Delete items from cart view</li><li>Clear items before re-ordering</li><li>Remove items from review cart</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/cart/get-cart.html">Get Cart</a></li><li><a href="/api/rest-api/shop/cart/add-to-cart.html">Add to Cart</a></li><li><a href="/api/rest-api/shop/cart/update-cart-item.html">Update Cart Item</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/cart/remove-cart-item.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const removeCartItem = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  removeCartItem as default
};
