import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Remove Coupon","description":"","frontmatter":{"outline":false,"examples":[{"id":"remove-coupon","title":"Remove Coupon from Cart","description":"Remove a discount coupon code from the shopping cart.","request":"DELETE /api/shop/cart/coupon\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\n","response":"{\\n  \\"message\\": \\"Coupon removed successfully\\",\\n  \\"cartTotal\\": 1199.98,\\n  \\"tax\\": 119.99,\\n  \\"total\\": 1319.97\\n}\\n","commonErrors":[{"error":"404 Not Found","cause":"No coupon currently applied","solution":"Apply a coupon first before removing"}]}]},"headers":[],"relativePath":"api/rest-api/shop/cart/remove-coupon.md","filePath":"api/rest-api/shop/cart/remove-coupon.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/cart/remove-coupon.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="remove-coupon" tabindex="-1">Remove Coupon <a class="header-anchor" href="#remove-coupon" aria-label="Permalink to &quot;Remove Coupon&quot;">​</a></h1><p>Remove a discount coupon code from the shopping cart.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DELETE /api/shop/cart/coupon</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr></tbody></table><h2 id="response-200-ok" tabindex="-1">Response (200 OK) <a class="header-anchor" href="#response-200-ok" aria-label="Permalink to &quot;Response (200 OK)&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;message&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Coupon removed successfully&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;cartTotal&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1199.98</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;tax&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">119.99</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;total&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1319.97</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>message</code></td><td>string</td><td>Success message</td></tr><tr><td><code>cartTotal</code></td><td>decimal</td><td>Updated cart subtotal</td></tr><tr><td><code>tax</code></td><td>decimal</td><td>Recalculated tax</td></tr><tr><td><code>total</code></td><td>decimal</td><td>New cart total</td></tr></tbody></table><h2 id="alternative-response-204-no-content" tabindex="-1">Alternative Response (204 No Content) <a class="header-anchor" href="#alternative-response-204-no-content" aria-label="Permalink to &quot;Alternative Response (204 No Content)&quot;">​</a></h2><p>No response body returned.</p><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Remove discount coupon from cart</li><li>Switch to different coupon</li><li>Cancel promotional discount</li><li>Clear coupon before re-applying</li></ul><h2 id="effects" tabindex="-1">Effects <a class="header-anchor" href="#effects" aria-label="Permalink to &quot;Effects&quot;">​</a></h2><ul><li>Discount amount is subtracted from cart</li><li>Cart total is recalculated</li><li>Tax may be recalculated based on new total</li><li>Cart items remain unchanged</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/cart/apply-coupon.html">Apply Coupon</a></li><li><a href="/api/rest-api/shop/cart/get-cart.html">Get Cart</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/cart/remove-coupon.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const removeCoupon = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  removeCoupon as default
};
