import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Customer Logout","description":"","frontmatter":{"outline":false,"examples":[{"id":"customer-logout","title":"Customer Logout","description":"Logout a customer and invalidate their authentication tokens.","query":"mutation createLogout  {\\n  createLogout(input: { }) {\\n    logout {\\n      success\\n      message\\n    }\\n  }\\n}\\n","variables":"{}\\n","response":"{\\n  \\"data\\": {\\n      \\"createLogout\\": {\\n          \\"logout\\": {\\n              \\"success\\": true,\\n              \\"message\\": \\"Logged out successfully\\"\\n          }\\n      }\\n  }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/customer-logout.md","filePath":"api/graphql-api/shop/mutations/customer-logout.md","lastUpdated":1771002662000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/customer-logout.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="customer-logout" tabindex="-1">Customer Logout <a class="header-anchor" href="#customer-logout" aria-label="Permalink to &quot;Customer Logout&quot;">​</a></h1><p>Logout a customer and invalidate their authentication tokens.</p><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This query requires a valid customer authentication token in the <code>Authorization</code> header. Use the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a> to retrieve the token.</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="response" tabindex="-1">Response <a class="header-anchor" href="#response" aria-label="Permalink to &quot;Response&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>message</code></td><td>String</td><td>Success or error message</td></tr><tr><td><code>success</code></td><td>Boolean</td><td>Logout success status</td></tr></tbody></table><h2 id="behavior" tabindex="-1">Behavior <a class="header-anchor" href="#behavior" aria-label="Permalink to &quot;Behavior&quot;">​</a></h2><ul><li>Invalidates the current access token</li><li>Invalidates the refresh token</li><li>Clears any session-related data</li><li>Customer will need to login again for future requests</li></ul><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;authentication&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Unauthorized: Invalid or expired token&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login</a></li><li><a href="/api/graphql-api/authentication.html">Authentication Guide</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/customer-logout.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const customerLogout = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  customerLogout as default
};
