import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Update Customer Address","description":"","frontmatter":{"outline":false,"examples":[{"id":"update-customer-address","title":"Update Customer Address","description":"Update an existing customer address.","request":"PUT /api/shop/customers/addresses/1\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\\n\\n{\\n  \\"firstName\\": \\"Jane\\",\\n  \\"lastName\\": \\"Doe\\",\\n  \\"address\\": \\"789 Pine Rd\\",\\n  \\"city\\": \\"Los Angeles\\",\\n  \\"state\\": \\"CA\\",\\n  \\"country\\": \\"US\\",\\n  \\"postcode\\": \\"90002\\",\\n  \\"phone\\": \\"9876543210\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"address\\": {\\n      \\"id\\": 1,\\n      \\"firstName\\": \\"Jane\\",\\n      \\"lastName\\": \\"Doe\\",\\n      \\"address\\": \\"789 Pine Rd\\",\\n      \\"city\\": \\"Los Angeles\\",\\n      \\"state\\": \\"CA\\",\\n      \\"country\\": \\"US\\",\\n      \\"postcode\\": \\"90002\\",\\n      \\"phone\\": \\"9876543210\\"\\n    }\\n  },\\n  \\"message\\": \\"Address updated successfully\\"\\n}\\n","commonErrors":[{"error":"401 Unauthorized","cause":"Customer not authenticated","solution":"Provide valid Bearer token"},{"error":"404 Not Found","cause":"Address does not exist","solution":"Verify the address ID"},{"error":"403 Forbidden","cause":"Address belongs to different customer","solution":"Only update your own addresses"}]}]},"headers":[],"relativePath":"api/rest-api/shop/customers/update-customer-address.md","filePath":"api/rest-api/shop/customers/update-customer-address.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/customers/update-customer-address.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="update-customer-address" tabindex="-1">Update Customer Address <a class="header-anchor" href="#update-customer-address" aria-label="Permalink to &quot;Update Customer Address&quot;">​</a></h1><p>Update an existing address in the customer&#39;s address book.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>PUT /api/shop/customers/addresses/{addressId}</span></span></code></pre></div><h2 id="url-parameters" tabindex="-1">URL Parameters <a class="header-anchor" href="#url-parameters" aria-label="Permalink to &quot;URL Parameters&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>addressId</code></td><td>integer</td><td>Yes</td><td>Address ID to update</td></tr></tbody></table><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr><tr><td><code>Authorization</code></td><td>Yes</td><td>Bearer token (customer login required)</td></tr></tbody></table><h2 id="request-body" tabindex="-1">Request Body <a class="header-anchor" href="#request-body" aria-label="Permalink to &quot;Request Body&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;firstName&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Jane&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;lastName&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Doe&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;address&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;789 Pine Rd&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;city&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Los Angeles&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;state&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;CA&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;country&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;US&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;postcode&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;90002&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;phone&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;9876543210&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="request-parameters" tabindex="-1">Request Parameters <a class="header-anchor" href="#request-parameters" aria-label="Permalink to &quot;Request Parameters&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>firstName</code></td><td>string</td><td>Yes</td><td>First name</td></tr><tr><td><code>lastName</code></td><td>string</td><td>Yes</td><td>Last name</td></tr><tr><td><code>address</code></td><td>string</td><td>Yes</td><td>Street address</td></tr><tr><td><code>city</code></td><td>string</td><td>Yes</td><td>City</td></tr><tr><td><code>state</code></td><td>string</td><td>Yes</td><td>State/Province</td></tr><tr><td><code>country</code></td><td>string</td><td>Yes</td><td>Country code</td></tr><tr><td><code>postcode</code></td><td>string</td><td>Yes</td><td>Postal code</td></tr><tr><td><code>phone</code></td><td>string</td><td>No</td><td>Phone number</td></tr></tbody></table><h2 id="response-fields-200-ok" tabindex="-1">Response Fields (200 OK) <a class="header-anchor" href="#response-fields-200-ok" aria-label="Permalink to &quot;Response Fields (200 OK)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>address</code></td><td>object</td><td>Updated address details</td></tr><tr><td><code>message</code></td><td>string</td><td>Success message</td></tr></tbody></table><h2 id="validation-rules" tabindex="-1">Validation Rules <a class="header-anchor" href="#validation-rules" aria-label="Permalink to &quot;Validation Rules&quot;">​</a></h2><ul><li>Address must belong to customer</li><li>All required fields must be provided</li><li>Country/State must be valid</li><li>Cannot update other customer&#39;s addresses</li></ul><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Correct address information</li><li>Update phone number</li><li>Change city/state</li><li>Modify street address</li><li>Update postal code</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/customers/get-customer-addresses.html">Get Customer Addresses</a></li><li><a href="/api/rest-api/shop/customers/create-customer-address.html">Create Customer Address</a></li><li><a href="/api/rest-api/shop/customers/delete-customer-address.html">Delete Customer Address</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/customers/update-customer-address.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const updateCustomerAddress = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  updateCustomerAddress as default
};
