import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Customer Registration","description":"","frontmatter":{"outline":false,"examples":[{"id":"customer-registration","title":"Customer Registration","description":"Register a new customer account with email and password.","query":"mutation registerCustomer($input: createCustomerInput!) {\\n  createCustomer(input: $input) {\\n    customer {\\n      id\\n      _id\\n      token\\n      channelId\\n      customerGroupId\\n      dateOfBirth\\n      email\\n      gender\\n      isSuspended\\n      isVerified\\n      name\\n      firstName\\n      lastName\\n      rememberToken\\n      subscribedToNewsLetter\\n      status\\n      phone\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"input\\": {\\n    \\"firstName\\": \\"John\\",\\n    \\"lastName\\": \\"Doe\\",\\n    \\"gender\\": \\"Male\\",\\n    \\"dateOfBirth\\": \\"01/15/1990\\",\\n    \\"phone\\": \\"555-0123\\",\\n    \\"status\\": \\"1\\",\\n    \\"isVerified\\": \\"1\\",\\n    \\"isSuspended\\": \\"0\\",\\n    \\"email\\": \\"john.doe@example.com\\",\\n    \\"password\\": \\"SecurePass@123\\",\\n    \\"confirmPassword\\": \\"SecurePass@123\\",\\n    \\"subscribedToNewsLetter\\": true\\n  }\\n}\\n","response":"{\\n    \\"data\\": {\\n        \\"createCustomer\\": {\\n            \\"customer\\": {\\n                \\"id\\": \\"/api/shop/customers/1\\",\\n                \\"_id\\": 1,\\n                \\"apiToken\\": \\"OOxDk2s06JCndg5FHb8WbfF6ZR8jGq23168m9gm37J9Cmz4xah8B8AFK0Cp95xoeztD1mDJV2eGRNTZ4\\",\\n                \\"channelId\\": null,\\n                \\"customerGroupId\\": null,\\n                \\"dateOfBirth\\": \\"1990-01-15\\",\\n                \\"email\\": \\"john.doe@example.com\\",\\n                \\"gender\\": \\"Male\\",\\n                \\"isSuspended\\": \\"0\\",\\n                \\"isVerified\\": \\"1\\",\\n                \\"name\\": \\"John Doe\\",\\n                \\"firstName\\": \\"John\\",\\n                \\"lastName\\": \\"Doe\\",\\n                \\"rememberToken\\": null,\\n                \\"subscribedToNewsLetter\\": true,\\n                \\"status\\": \\"1\\",\\n                \\"token\\": \\"7b65c50e0c15cdc684d36e5819eb7c19\\",\\n                \\"phone\\": \\"555-0123\\"\\n            }\\n        }\\n    }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/customer-registration.md","filePath":"api/graphql-api/shop/mutations/customer-registration.md","lastUpdated":1771002662000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/customer-registration.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="customer-registration" tabindex="-1">Customer Registration <a class="header-anchor" href="#customer-registration" aria-label="Permalink to &quot;Customer Registration&quot;">​</a></h1><p>Register a new customer account with Bagisto.</p><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>firstName</code></td><td>String</td><td>✅ Yes</td><td>Customer&#39;s first name</td></tr><tr><td><code>lastName</code></td><td>String</td><td>✅ Yes</td><td>Customer&#39;s last name</td></tr><tr><td><code>email</code></td><td>String</td><td>✅ Yes</td><td>Customer&#39;s email address (must be unique)</td></tr><tr><td><code>password</code></td><td>String</td><td>✅ Yes</td><td>Password for the account (min. 8 characters)</td></tr><tr><td><code>passwordConfirmation</code></td><td>String</td><td>✅ Yes</td><td>Password confirmation (must match password)</td></tr></tbody></table><h2 id="response" tabindex="-1">Response <a class="header-anchor" href="#response" aria-label="Permalink to &quot;Response&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>customer</code></td><td>Customer</td><td>The created customer object</td></tr><tr><td><code>accessToken</code></td><td>String</td><td>JWT token for API authentication</td></tr><tr><td><code>refreshToken</code></td><td>String</td><td>Token to refresh access token</td></tr><tr><td><code>message</code></td><td>String</td><td>Success or error message</td></tr><tr><td><code>success</code></td><td>Boolean</td><td>Registration success status</td></tr></tbody></table><h2 id="validation-rules" tabindex="-1">Validation Rules <a class="header-anchor" href="#validation-rules" aria-label="Permalink to &quot;Validation Rules&quot;">​</a></h2><ul><li>Email must be in valid format and unique</li><li>Password must be at least 8 characters</li><li>Password and password confirmation must match</li><li>First name and last name are required</li><li>Email cannot already exist in the system</li></ul><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;email&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;The email has already been taken.&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;password&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;The password must be at least 8 characters.&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login</a></li><li><a href="/api/graphql-api/shop/mutations/update-customer-profile.html">Update Customer Profile</a></li><li><a href="/api/graphql-api/authentication.html">Authentication Guide</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/customer-registration.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const customerRegistration = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  customerRegistration as default
};
