import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse(`{"title":"Update Customer Profile","description":"","frontmatter":{"outline":false,"examples":[{"id":"update-customer-profile","title":"Update Customer Profile","description":"Update the authenticated customer's profile information.","request":"PUT /api/shop/customers/profile\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\\n\\n{\\n  \\"firstName\\": \\"John\\",\\n  \\"lastName\\": \\"Doe\\",\\n  \\"email\\": \\"john.doe@example.com\\",\\n  \\"phone\\": \\"1234567890\\",\\n  \\"gender\\": \\"M\\",\\n  \\"dateOfBirth\\": \\"1990-01-15\\"\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"customer\\": {\\n      \\"id\\": 1,\\n      \\"firstName\\": \\"John\\",\\n      \\"lastName\\": \\"Doe\\",\\n      \\"email\\": \\"john.doe@example.com\\",\\n      \\"phone\\": \\"1234567890\\",\\n      \\"gender\\": \\"M\\",\\n      \\"dateOfBirth\\": \\"1990-01-15\\",\\n      \\"updatedAt\\": \\"2024-01-15T10:30:00Z\\"\\n    }\\n  },\\n  \\"message\\": \\"Profile updated successfully\\"\\n}\\n","commonErrors":[{"error":"401 Unauthorized","cause":"Customer not authenticated","solution":"Provide valid Bearer token"},{"error":"422 Unprocessable Entity","cause":"Email already exists","solution":"Use unique email address"},{"error":"400 Bad Request","cause":"Invalid data format","solution":"Verify all fields match required format"}]}]},"headers":[],"relativePath":"api/rest-api/shop/customers/update-customer-profile.md","filePath":"api/rest-api/shop/customers/update-customer-profile.md","lastUpdated":1770102569000}`);
const _sfc_main = { name: "api/rest-api/shop/customers/update-customer-profile.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="update-customer-profile" tabindex="-1">Update Customer Profile <a class="header-anchor" href="#update-customer-profile" aria-label="Permalink to &quot;Update Customer Profile&quot;">​</a></h1><p>Update the authenticated customer&#39;s profile information.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>PUT /api/shop/customers/profile</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr><tr><td><code>Authorization</code></td><td>Yes</td><td>Bearer token (customer login required)</td></tr></tbody></table><h2 id="request-body" tabindex="-1">Request Body <a class="header-anchor" href="#request-body" aria-label="Permalink to &quot;Request Body&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;firstName&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;John&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;lastName&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Doe&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;email&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;john.doe@example.com&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;phone&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;1234567890&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;gender&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;M&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;dateOfBirth&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;1990-01-15&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="request-parameters" tabindex="-1">Request Parameters <a class="header-anchor" href="#request-parameters" aria-label="Permalink to &quot;Request Parameters&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>firstName</code></td><td>string</td><td>Yes</td><td>First name (max 255 chars)</td></tr><tr><td><code>lastName</code></td><td>string</td><td>Yes</td><td>Last name (max 255 chars)</td></tr><tr><td><code>email</code></td><td>string</td><td>Yes</td><td>Valid email address</td></tr><tr><td><code>phone</code></td><td>string</td><td>No</td><td>Phone number</td></tr><tr><td><code>gender</code></td><td>string</td><td>No</td><td>Gender (M/F/Other)</td></tr><tr><td><code>dateOfBirth</code></td><td>string</td><td>No</td><td>Birth date (YYYY-MM-DD)</td></tr></tbody></table><h2 id="response-fields-200-ok" tabindex="-1">Response Fields (200 OK) <a class="header-anchor" href="#response-fields-200-ok" aria-label="Permalink to &quot;Response Fields (200 OK)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>customer</code></td><td>object</td><td>Updated customer profile</td></tr><tr><td><code>message</code></td><td>string</td><td>Success message</td></tr></tbody></table><h2 id="validation-rules" tabindex="-1">Validation Rules <a class="header-anchor" href="#validation-rules" aria-label="Permalink to &quot;Validation Rules&quot;">​</a></h2><ul><li>First name: required, max 255 characters</li><li>Last name: required, max 255 characters</li><li>Email: must be unique, valid format</li><li>Phone: optional, valid format</li><li>Date of birth: optional, valid date format</li></ul><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Update account information</li><li>Change email address</li><li>Modify personal details</li><li>Update phone number</li><li>Add/change birth date</li></ul><h2 id="important-notes" tabindex="-1">Important Notes <a class="header-anchor" href="#important-notes" aria-label="Permalink to &quot;Important Notes&quot;">​</a></h2><ul><li>Changing email requires verification</li><li>Some fields may be locked by admin</li><li>Updates reflected immediately</li><li>Original email may be required for verification</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/customers/get-customer-profile.html">Get Customer Profile</a></li><li><a href="/api/rest-api/shop/customers/delete-customer-profile.html">Delete Customer Profile</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/customers/update-customer-profile.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const updateCustomerProfile = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  updateCustomerProfile as default
};
