import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Get Shipping Methods","description":"","frontmatter":{"outline":false,"examples":[{"id":"get-shipping-methods","title":"Get Available Shipping Methods","description":"Retrieve available shipping methods for checkout.","request":"GET /api/shop/checkout/shipping-methods\\nContent-Type: application/json\\nX-STOREFRONT-KEY: pk_storefront_PvlE42nWGsKRVIf8bDlJngTPAdWAZbIy\\n\\n{\\n  \\"country\\": \\"US\\",\\n  \\"state\\": \\"NY\\",\\n  \\"postcode\\": \\"10001\\"\\n}\\n","response":"{\\n  \\"data\\": [\\n    {\\n      \\"id\\": 1,\\n      \\"code\\": \\"standard\\",\\n      \\"name\\": \\"Standard Shipping\\",\\n      \\"description\\": \\"Delivery in 5-7 business days\\",\\n      \\"price\\": 10.00,\\n      \\"estimatedDays\\": 7\\n    },\\n    {\\n      \\"id\\": 2,\\n      \\"code\\": \\"express\\",\\n      \\"name\\": \\"Express Shipping\\",\\n      \\"description\\": \\"Delivery in 2-3 business days\\",\\n      \\"price\\": 25.00,\\n      \\"estimatedDays\\": 3\\n    }\\n  ]\\n}\\n","commonErrors":[{"error":"422 Validation Error","cause":"Invalid location data","solution":"Provide valid country, state, and postcode"},{"error":"400 Bad Request","cause":"No shipping methods available for location","solution":"Check location or contact support"}]}]},"headers":[],"relativePath":"api/rest-api/shop/checkout/get-shipping-methods.md","filePath":"api/rest-api/shop/checkout/get-shipping-methods.md","lastUpdated":1770102569000}');
const _sfc_main = { name: "api/rest-api/shop/checkout/get-shipping-methods.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="get-shipping-methods" tabindex="-1">Get Shipping Methods <a class="header-anchor" href="#get-shipping-methods" aria-label="Permalink to &quot;Get Shipping Methods&quot;">​</a></h1><p>Retrieve available shipping methods based on address and cart contents.</p><h2 id="endpoint" tabindex="-1">Endpoint <a class="header-anchor" href="#endpoint" aria-label="Permalink to &quot;Endpoint&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>POST /api/shop/checkout/shipping-methods</span></span></code></pre></div><h2 id="request-headers" tabindex="-1">Request Headers <a class="header-anchor" href="#request-headers" aria-label="Permalink to &quot;Request Headers&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Header</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>Content-Type</code></td><td>Yes</td><td>application/json</td></tr><tr><td><code>X-STOREFRONT-KEY</code></td><td>Yes</td><td>Your storefront API key</td></tr></tbody></table><h2 id="request-body" tabindex="-1">Request Body <a class="header-anchor" href="#request-body" aria-label="Permalink to &quot;Request Body&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;country&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;US&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;state&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;NY&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;postcode&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;10001&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>country</code></td><td>string</td><td>Yes</td><td>Country code (ISO)</td></tr><tr><td><code>state</code></td><td>string</td><td>Yes</td><td>State/Province code</td></tr><tr><td><code>postcode</code></td><td>string</td><td>Yes</td><td>Postal code</td></tr></tbody></table><h2 id="response-fields-200-ok" tabindex="-1">Response Fields (200 OK) <a class="header-anchor" href="#response-fields-200-ok" aria-label="Permalink to &quot;Response Fields (200 OK)&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td>integer</td><td>Shipping method ID</td></tr><tr><td><code>code</code></td><td>string</td><td>Shipping method code</td></tr><tr><td><code>name</code></td><td>string</td><td>Display name</td></tr><tr><td><code>description</code></td><td>string</td><td>Method description</td></tr><tr><td><code>price</code></td><td>decimal</td><td>Shipping cost</td></tr><tr><td><code>estimatedDays</code></td><td>integer</td><td>Estimated delivery days</td></tr><tr><td><code>maxDeliveryDate</code></td><td>string</td><td>Expected delivery date</td></tr></tbody></table><h2 id="use-cases" tabindex="-1">Use Cases <a class="header-anchor" href="#use-cases" aria-label="Permalink to &quot;Use Cases&quot;">​</a></h2><ul><li>Display shipping options during checkout</li><li>Calculate shipping cost</li><li>Allow customer to select shipping method</li><li>Show delivery estimates</li><li>Filter methods by location</li></ul><h2 id="notes" tabindex="-1">Notes <a class="header-anchor" href="#notes" aria-label="Permalink to &quot;Notes&quot;">​</a></h2><ul><li>Methods vary by location and product</li><li>Prices may be calculated dynamically</li><li>Some methods may have weight/dimension limits</li><li>International shipping may have restrictions</li></ul><h2 id="related-resources" tabindex="-1">Related Resources <a class="header-anchor" href="#related-resources" aria-label="Permalink to &quot;Related Resources&quot;">​</a></h2><ul><li><a href="/api/rest-api/shop/checkout/set-shipping-method.html">Set Shipping Method</a></li><li><a href="/api/rest-api/shop/checkout/get-payment-methods.html">Get Payment Methods</a></li><li><a href="/api/rest-api/shop/checkout/get-addresses.html">Get Checkout Addresses</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/rest-api/shop/checkout/get-shipping-methods.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getShippingMethods = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getShippingMethods as default
};
