import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Delete Wishlist Item","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-wishlist-basic","title":"Delete Wishlist Item","description":"Delete a specific wishlist item by its IRI.","query":"mutation DeleteWishlist($input: deleteWishlistInput!) {\\n  deleteWishlist(input: $input) {\\n    wishlist {\\n      id\\n      _id\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"input\\": {\\n    \\"id\\": \\"/api/shop/wishlists/69\\"\\n  }\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"deleteWishlist\\": {\\n      \\"wishlist\\": {\\n        \\"id\\": \\"/api/shop/wishlists/69\\",\\n        \\"_id\\": 69\\n      }\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"},{"error":"ITEM_NOT_FOUND","cause":"Wishlist item does not exist or belongs to another customer","solution":"Use a valid wishlist item IRI from the wishlists collection query"}]}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/delete-wishlist.md","filePath":"api/graphql-api/shop/mutations/delete-wishlist.md","lastUpdated":1771348498000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/delete-wishlist.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-wishlist-item" tabindex="-1">Delete Wishlist Item <a class="header-anchor" href="#delete-wishlist-item" aria-label="Permalink to &quot;Delete Wishlist Item&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>deleteWishlist</code> mutation removes a specific item from the authenticated customer&#39;s wishlist. Use this mutation to:</p><ul><li>Remove individual products from the wishlist</li><li>Implement &quot;Remove from Wishlist&quot; buttons</li><li>Clean up wishlist items programmatically</li></ul><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This mutation requires customer authentication:</p><ul><li><strong>Authenticated customers</strong>: Provide a valid customer authentication token in the <code>Authorization</code> header. Obtain this token via the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a>.</li></ul><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>The IRI of the wishlist item to delete (e.g. <code>/api/shop/wishlists/69</code>).</td></tr><tr><td><code>clientMutationId</code></td><td><code>String</code></td><td>Optional client-side mutation identifier for tracking.</td></tr></tbody></table><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>wishlist</code></td><td><code>Wishlist!</code></td><td>The deleted wishlist item.</td></tr><tr><td><code>wishlist.id</code></td><td><code>ID!</code></td><td>IRI identifier of the removed item.</td></tr><tr><td><code>wishlist._id</code></td><td><code>Int!</code></td><td>Numeric identifier of the removed item.</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/delete-wishlist.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteWishlist = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteWishlist as default
};
