import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Delete All Wishlist Items","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-all-wishlists","title":"Delete All Wishlist Items","description":"Remove all wishlist items for the authenticated customer. Returns the count of deleted items.","query":"mutation DeleteAllWishlists {\\n  createDeleteAllWishlists(input: {}) {\\n    deleteAllWishlists {\\n      message\\n      deletedCount\\n    }\\n  }\\n}\\n","variables":"{}\\n","response":"{\\n  \\"data\\": {\\n    \\"createDeleteAllWishlists\\": {\\n      \\"deleteAllWishlists\\": {\\n        \\"message\\": \\"All wishlist items have been removed successfully\\",\\n        \\"deletedCount\\": 3\\n      }\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"}]},{"id":"delete-all-wishlists-empty","title":"Delete All Wishlist Items - No Items","description":"Calling delete all when the customer has no wishlist items returns a zero deleted count.","query":"mutation DeleteAllWishlists {\\n  createDeleteAllWishlists(input: {}) {\\n    deleteAllWishlists {\\n      message\\n      deletedCount\\n    }\\n  }\\n}\\n","variables":"{}\\n","response":"{\\n  \\"data\\": {\\n    \\"createDeleteAllWishlists\\": {\\n      \\"deleteAllWishlists\\": {\\n        \\"message\\": \\"All wishlist items have been removed successfully\\",\\n        \\"deletedCount\\": 0\\n      }\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"}]}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/delete-all-wishlists.md","filePath":"api/graphql-api/shop/mutations/delete-all-wishlists.md","lastUpdated":1771348498000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/delete-all-wishlists.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-all-wishlist-items" tabindex="-1">Delete All Wishlist Items <a class="header-anchor" href="#delete-all-wishlist-items" aria-label="Permalink to &quot;Delete All Wishlist Items&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>createDeleteAllWishlists</code> mutation removes all items from the authenticated customer&#39;s wishlist at once. Use this mutation to:</p><ul><li>Clear the entire wishlist</li><li>Implement a &quot;Clear All&quot; button on the wishlist page</li><li>Reset the customer&#39;s wishlist state</li></ul><blockquote><p><strong>Note:</strong> This is an authenticated-only operation. The customer is auto-detected from the Bearer token.</p></blockquote><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This mutation requires customer authentication:</p><ul><li><strong>Authenticated customers</strong>: Provide a valid customer authentication token in the <code>Authorization</code> header. Obtain this token via the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a>.</li></ul><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>clientMutationId</code></td><td><code>String</code></td><td>Optional client-side mutation identifier for tracking.</td></tr></tbody></table><blockquote><p><strong>Note:</strong> No additional input is required. Pass an empty input <code>{}</code>.</p></blockquote><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>deleteAllWishlists.message</code></td><td><code>String!</code></td><td>Success message confirming deletion.</td></tr><tr><td><code>deleteAllWishlists.deletedCount</code></td><td><code>Int!</code></td><td>Number of wishlist items that were removed.</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/delete-all-wishlists.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteAllWishlists = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteAllWishlists as default
};
