import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Delete Customer Address","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-customer-address","title":"Delete Customer Address","description":"Delete a customer address.","query":"mutation deleteCustomerAddress($input: createDeleteCustomerAddressInput!) {\\n  createDeleteCustomerAddress(input: $input) {\\n    deleteCustomerAddress {\\n      id\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"input\\": {\\n    \\"addressId\\": 2858\\n  }\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"createDeleteCustomerAddress\\": {\\n      \\"deleteCustomerAddress\\": {\\n        \\"id\\": \\"2858\\"\\n      }\\n    }\\n  }\\n}\\n"}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/delete-customer-address.md","filePath":"api/graphql-api/shop/mutations/delete-customer-address.md","lastUpdated":1771002662000}');
const _sfc_main = { name: "api/graphql-api/shop/mutations/delete-customer-address.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-customer-address" tabindex="-1">Delete Customer Address <a class="header-anchor" href="#delete-customer-address" aria-label="Permalink to &quot;Delete Customer Address&quot;">​</a></h1><p>Delete a customer address.</p><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This query requires a valid customer authentication token in the <code>Authorization</code> header. Use the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a> to retrieve the token.</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td><code>addressId</code></td><td>String</td><td>✅ Yes</td><td>Address ID to delete</td></tr></tbody></table><h2 id="response" tabindex="-1">Response <a class="header-anchor" href="#response" aria-label="Permalink to &quot;Response&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>createDeleteCustomerAddress</code></td><td>String</td><td>Return deleted customer address object</td></tr></tbody></table><h2 id="important-notes" tabindex="-1">Important Notes <a class="header-anchor" href="#important-notes" aria-label="Permalink to &quot;Important Notes&quot;">​</a></h2><ul><li>Address must belong to the authenticated customer</li><li>Default address cannot be deleted without setting a new default</li><li>Addresses used in incomplete orders may be archived instead of deleted</li></ul><h2 id="error-responses" tabindex="-1">Error Responses <a class="header-anchor" href="#error-responses" aria-label="Permalink to &quot;Error Responses&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;errors&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;message&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Address not found or does not belong to this customer&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="related-documentation" tabindex="-1">Related Documentation <a class="header-anchor" href="#related-documentation" aria-label="Permalink to &quot;Related Documentation&quot;">​</a></h2><ul><li><a href="/api/graphql-api/shop/mutations/create-customer-address.html">Create Customer Address</a></li><li><a href="/api/graphql-api/shop/mutations/update-customer-address.html">Update Customer Address</a></li><li><a href="/api/graphql-api/shop/queries/get-customer-addresses.html">Get Customer Addresses</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/delete-customer-address.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteCustomerAddress = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteCustomerAddress as default
};
