import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse(`{"title":"Delete Compare Item","description":"","frontmatter":{"outline":false,"examples":[{"id":"delete-compare-item-basic","title":"Remove Product from Compare List","description":"Remove a product from the customer's comparison list by its IRI.","query":"mutation DeleteCompareItem($input: deleteCompareItemInput!) {\\n  deleteCompareItem(input: $input) {\\n    compareItem {\\n      id\\n      product {\\n        sku\\n        type\\n        createdAt\\n      }\\n    }\\n  }\\n}\\n","variables":"{\\n  \\"input\\": {\\n    \\"id\\": \\"/api/shop/compare-items/606\\"\\n  }\\n}\\n","response":"{\\n  \\"data\\": {\\n    \\"deleteCompareItem\\": {\\n      \\"compareItem\\": {\\n        \\"id\\": \\"/api/shop/compare-items/606\\",\\n        \\"product\\": {\\n          \\"sku\\": \\"LP15-2026\\",\\n          \\"type\\": \\"simple\\",\\n          \\"createdAt\\": \\"2026-02-01T08:00:00+00:00\\"\\n        }\\n      }\\n    }\\n  }\\n}\\n","commonErrors":[{"error":"UNAUTHENTICATED","cause":"Missing or invalid Bearer token","solution":"Login and provide a valid customer authentication token"},{"error":"ITEM_NOT_FOUND","cause":"Compare item does not exist or belongs to another customer","solution":"Use a valid compare item IRI from the compareItems collection query"}]}]},"headers":[],"relativePath":"api/graphql-api/shop/mutations/delete-compare-item.md","filePath":"api/graphql-api/shop/mutations/delete-compare-item.md","lastUpdated":1771348498000}`);
const _sfc_main = { name: "api/graphql-api/shop/mutations/delete-compare-item.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="delete-compare-item" tabindex="-1">Delete Compare Item <a class="header-anchor" href="#delete-compare-item" aria-label="Permalink to &quot;Delete Compare Item&quot;">​</a></h1><h2 id="about" tabindex="-1">About <a class="header-anchor" href="#about" aria-label="Permalink to &quot;About&quot;">​</a></h2><p>The <code>deleteCompareItem</code> mutation removes a product from the authenticated customer&#39;s comparison list. Use this mutation to:</p><ul><li>Remove individual products from the compare list</li><li>Implement &quot;Remove from Compare&quot; buttons</li><li>Clean up comparison lists programmatically</li></ul><h2 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h2><p>This mutation requires customer authentication:</p><ul><li><strong>Authenticated customers</strong>: Provide a valid customer authentication token in the <code>Authorization</code> header. Obtain this token via the <a href="/api/graphql-api/shop/mutations/customer-login.html">Customer Login API</a>.</li></ul><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Authorization: Bearer &lt;accessToken&gt;</span></span></code></pre></div><h2 id="arguments" tabindex="-1">Arguments <a class="header-anchor" href="#arguments" aria-label="Permalink to &quot;Arguments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Argument</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>ID!</code></td><td>The IRI of the compare item to delete (e.g. <code>/api/shop/compare-items/606</code>).</td></tr><tr><td><code>clientMutationId</code></td><td><code>String</code></td><td>Optional client-side mutation identifier for tracking.</td></tr></tbody></table><h2 id="possible-returns" tabindex="-1">Possible Returns <a class="header-anchor" href="#possible-returns" aria-label="Permalink to &quot;Possible Returns&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>compareItem</code></td><td><code>CompareItem!</code></td><td>The deleted compare item.</td></tr><tr><td><code>compareItem.id</code></td><td><code>ID!</code></td><td>IRI identifier of the removed item.</td></tr><tr><td><code>compareItem.product</code></td><td><code>Product!</code></td><td>Product details of the removed item.</td></tr></tbody></table></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/graphql-api/shop/mutations/delete-compare-item.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const deleteCompareItem = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  deleteCompareItem as default
};
